about
SkrypnykPavlo/G13-Ice-Cream pull request #10
Opened 2022-10-15 19:54 UTC by AnnaRed1982

2022-10-15 20:17 UTC, Yevhenii-Boiko approved these changes

2022-10-15 20:30 UTC, Yevhenii-Boiko approved these changes

2022-10-15 21:36 UTC, SkrypnykPavlo requested changes
потрібно звірити _about.scss з файлами стилів base/_normalize.scss і components/_container.scss бо частина стилів вже вказана в них

2022-10-15 22:45 UTC, AnnaRed1982 commented
> потрібно звірити _about.scss з файлами стилів base/_normalize.scss і components/_container.scss бо частина стилів вже вказана в них

зробила зміни стилів

2022-10-16 10:55 UTC, SkrypnykPavlo approved these changes

2022-10-16 10:55 UTC, merged